#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using PortalProModelo;

namespace PortalProModelo	
{
	public partial class GrupoUsuario
	{
		private int _grupoUsuarioId;
		public virtual int GrupoUsuarioId
		{
			get
			{
				return this._grupoUsuarioId;
			}
			set
			{
				this._grupoUsuarioId = value;
			}
		}
		
		private string _nombre;
		public virtual string Nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private IList<Usuario> _usuarios = new List<Usuario>();
		public virtual IList<Usuario> Usuarios
		{
			get
			{
				return this._usuarios;
			}
		}
		
	}
}
#pragma warning restore 1591
