#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using PortalProModelo;

namespace PortalProModelo	
{
	public partial class GrupoProveedor
	{
		private int _grupoProveedorId;
		public virtual int GrupoProveedorId
		{
			get
			{
				return this._grupoProveedorId;
			}
			set
			{
				this._grupoProveedorId = value;
			}
		}
		
		private string _nombre;
		public virtual string Nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private IList<TipoDocumentoGrupoProveedor> _tipoDocumentoGrupoProveedors = new List<TipoDocumentoGrupoProveedor>();
		public virtual IList<TipoDocumentoGrupoProveedor> TipoDocumentoGrupoProveedors
		{
			get
			{
				return this._tipoDocumentoGrupoProveedors;
			}
		}
		
		private IList<Proveedor> _proveedors = new List<Proveedor>();
		public virtual IList<Proveedor> Proveedors
		{
			get
			{
				return this._proveedors;
			}
		}
		
		private IList<SolicitudProveedor> _solicitudProveedors = new List<SolicitudProveedor>();
		public virtual IList<SolicitudProveedor> SolicitudProveedors
		{
			get
			{
				return this._solicitudProveedors;
			}
		}
		
	}
}
#pragma warning restore 1591
