#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace PortalProModelo	
{
	public partial class Parametro
	{
		private int _parametroId;
		public virtual int ParametroId
		{
			get
			{
				return this._parametroId;
			}
			set
			{
				this._parametroId = value;
			}
		}
		
		private bool _facturaAbierto;
		public virtual bool FacturaAbierto
		{
			get
			{
				return this._facturaAbierto;
			}
			set
			{
				this._facturaAbierto = value;
			}
		}
		
		private int _maxFichero;
		public virtual int MaxFichero
		{
			get
			{
				return this._maxFichero;
			}
			set
			{
				this._maxFichero = value;
			}
		}
		
		private int _margenFactura;
		public virtual int MargenFactura
		{
			get
			{
				return this._margenFactura;
			}
			set
			{
				this._margenFactura = value;
			}
		}
		
	}
}
#pragma warning restore 1591
