#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using PortalProModelo;

namespace PortalProModelo	
{
	public partial class SolicitudLog
	{
		private int _solicitudLogId;
		public virtual int SolicitudLogId
		{
			get
			{
				return this._solicitudLogId;
			}
			set
			{
				this._solicitudLogId = value;
			}
		}
		
		private DateTime _sello;
		public virtual DateTime Sello
		{
			get
			{
				return this._sello;
			}
			set
			{
				this._sello = value;
			}
		}
		
		private string _comentarios;
		public virtual string Comentarios
		{
			get
			{
				return this._comentarios;
			}
			set
			{
				this._comentarios = value;
			}
		}
		
		private Usuario _usuario;
		public virtual Usuario Usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				this._usuario = value;
			}
		}
		
		private SolicitudStatus _solicitudStatus;
		public virtual SolicitudStatus SolicitudStatusInicial
		{
			get
			{
				return this._solicitudStatus;
			}
			set
			{
				this._solicitudStatus = value;
			}
		}
		
		private SolicitudStatus _solicitudStatus1;
		public virtual SolicitudStatus SolicitudStatusFinal
		{
			get
			{
				return this._solicitudStatus1;
			}
			set
			{
				this._solicitudStatus1 = value;
			}
		}
		
		private SolicitudProveedor _solicitudProveedor;
		public virtual SolicitudProveedor SolicitudProveedor
		{
			get
			{
				return this._solicitudProveedor;
			}
			set
			{
				this._solicitudProveedor = value;
			}
		}
		
	}
}
#pragma warning restore 1591
