#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using PortalProModelo;

namespace PortalProModelo	
{
	public partial class TipoDocumento
	{
		private int _tipoDocumentoId;
		public virtual int TipoDocumentoId
		{
			get
			{
				return this._tipoDocumentoId;
			}
			set
			{
				this._tipoDocumentoId = value;
			}
		}
		
		private string _nombre;
		public virtual string Nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private bool _obligatorio;
		public virtual bool Obligatorio
		{
			get
			{
				return this._obligatorio;
			}
			set
			{
				this._obligatorio = value;
			}
		}
		
		private IList<TipoDocumentoGrupoProveedor> _tipoDocumentoGrupoProveedors = new List<TipoDocumentoGrupoProveedor>();
		public virtual IList<TipoDocumentoGrupoProveedor> TipoDocumentoGrupoProveedors
		{
			get
			{
				return this._tipoDocumentoGrupoProveedors;
			}
		}
		
		private IList<Documento> _documentos = new List<Documento>();
		public virtual IList<Documento> Documentos
		{
			get
			{
				return this._documentos;
			}
		}
		
	}
}
#pragma warning restore 1591
