#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using PortalProModelo;


namespace PortalProModelo	
{
	public partial class TipoDocumento
	{
		private int _tipoDocumentoId;
		public virtual int TipoDocumentoId 
		{ 
		    get
		    {
		        return this._tipoDocumentoId;
		    }
		    set
		    {
		        this._tipoDocumentoId = value;
		    }
		}
		
		private string _nombre;
		public virtual string Nombre 
		{ 
		    get
		    {
		        return this._nombre;
		    }
		    set
		    {
		        this._nombre = value;
		    }
		}
		
		private IList<TipoDocumentoGrupoProveedor> _tipoDocumentoGrupoProveedors = new List<TipoDocumentoGrupoProveedor>();
		public virtual IList<TipoDocumentoGrupoProveedor> TipoDocumentoGrupoProveedors 
		{ 
		    get
		    {
		        return this._tipoDocumentoGrupoProveedors;
		    }
		}
		
	}
}
