#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using PortalProModelo;


namespace PortalProModelo	
{
	public partial class WebApiTicket
	{
		private int _webApiTicketId;
		public virtual int WebApiTicketId 
		{ 
		    get
		    {
		        return this._webApiTicketId;
		    }
		    set
		    {
		        this._webApiTicketId = value;
		    }
		}
		
		private DateTime _inicio;
		public virtual DateTime Inicio 
		{ 
		    get
		    {
		        return this._inicio;
		    }
		    set
		    {
		        this._inicio = value;
		    }
		}
		
		private DateTime _fin;
		public virtual DateTime Fin 
		{ 
		    get
		    {
		        return this._fin;
		    }
		    set
		    {
		        this._fin = value;
		    }
		}
		
		private string _codigo;
		public virtual string Codigo 
		{ 
		    get
		    {
		        return this._codigo;
		    }
		    set
		    {
		        this._codigo = value;
		    }
		}
		
		private Usuario _usuario;
		public virtual Usuario Usuario 
		{ 
		    get
		    {
		        return this._usuario;
		    }
		    set
		    {
		        this._usuario = value;
		    }
		}
		
	}
}
