#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace PortalProAxapta	
{
	public partial class Cau_PortalPro_VCabPedido
	{
		private string _pURCHID;
		public virtual string PURCHID
		{
			get
			{
				return this._pURCHID;
			}
			set
			{
				this._pURCHID = value;
			}
		}
		
		private string _iNVOICEACCOUNT;
		public virtual string INVOICEACCOUNT
		{
			get
			{
				return this._iNVOICEACCOUNT;
			}
			set
			{
				this._iNVOICEACCOUNT = value;
			}
		}
		
		private string _dATAAREAID;
		public virtual string DATAAREAID
		{
			get
			{
				return this._dATAAREAID;
			}
			set
			{
				this._dATAAREAID = value;
			}
		}
		
		private string _eSTADO;
		public virtual string ESTADO
		{
			get
			{
				return this._eSTADO;
			}
			set
			{
				this._eSTADO = value;
			}
		}
		
		private string _tIPO;
		public virtual string TIPO
		{
			get
			{
				return this._tIPO;
			}
			set
			{
				this._tIPO = value;
			}
		}
		
		private string _cODCONTACTO;
		public virtual string CODCONTACTO
		{
			get
			{
				return this._cODCONTACTO;
			}
			set
			{
				this._cODCONTACTO = value;
			}
		}
		
		private string _cONTACTO;
		public virtual string CONTACTO
		{
			get
			{
				return this._cONTACTO;
			}
			set
			{
				this._cONTACTO = value;
			}
		}
		
		private DateTime _cREATEDDATE;
		public virtual DateTime CREATEDDATE
		{
			get
			{
				return this._cREATEDDATE;
			}
			set
			{
				this._cREATEDDATE = value;
			}
		}
		
		private DateTime? _fECHARECEPCION;
		public virtual DateTime? FECHARECEPCION
		{
			get
			{
				return this._fECHARECEPCION;
			}
			set
			{
				this._fECHARECEPCION = value;
			}
		}
		
		private DateTime? _fECHALIMITE;
		public virtual DateTime? FECHALIMITE
		{
			get
			{
				return this._fECHALIMITE;
			}
			set
			{
				this._fECHALIMITE = value;
			}
		}
		
	}
}
#pragma warning restore 1591
