#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace PortalProAxapta	
{
	public partial class Cau_PortalPro_VProveedore
	{
		private string _aCCOUNTNUM;
		public virtual string ACCOUNTNUM
		{
			get
			{
				return this._aCCOUNTNUM;
			}
			set
			{
				this._aCCOUNTNUM = value;
			}
		}
		
		private string _nAME;
		public virtual string NAME
		{
			get
			{
				return this._nAME;
			}
			set
			{
				this._nAME = value;
			}
		}
		
		private string _aDDRESS;
		public virtual string ADDRESS
		{
			get
			{
				return this._aDDRESS;
			}
			set
			{
				this._aDDRESS = value;
			}
		}
		
		private string _cITY;
		public virtual string CITY
		{
			get
			{
				return this._cITY;
			}
			set
			{
				this._cITY = value;
			}
		}
		
		private string _zIPCODE;
		public virtual string ZIPCODE
		{
			get
			{
				return this._zIPCODE;
			}
			set
			{
				this._zIPCODE = value;
			}
		}
		
		private string _cOUNTRYREGIONID;
		public virtual string COUNTRYREGIONID
		{
			get
			{
				return this._cOUNTRYREGIONID;
			}
			set
			{
				this._cOUNTRYREGIONID = value;
			}
		}
		
		private string _pHONE;
		public virtual string PHONE
		{
			get
			{
				return this._pHONE;
			}
			set
			{
				this._pHONE = value;
			}
		}
		
		private string _tELEFAX;
		public virtual string TELEFAX
		{
			get
			{
				return this._tELEFAX;
			}
			set
			{
				this._tELEFAX = value;
			}
		}
		
		private string _cELLULARPHONE;
		public virtual string CELLULARPHONE
		{
			get
			{
				return this._cELLULARPHONE;
			}
			set
			{
				this._cELLULARPHONE = value;
			}
		}
		
		private string _eMAIL;
		public virtual string EMAIL
		{
			get
			{
				return this._eMAIL;
			}
			set
			{
				this._eMAIL = value;
			}
		}
		
		private string _vATNUM;
		public virtual string VATNUM
		{
			get
			{
				return this._vATNUM;
			}
			set
			{
				this._vATNUM = value;
			}
		}
		
		private string _cONTACTO;
		public virtual string CONTACTO
		{
			get
			{
				return this._cONTACTO;
			}
			set
			{
				this._cONTACTO = value;
			}
		}
		
		private string _lINEOFBUSINESSID;
		public virtual string LINEOFBUSINESSID
		{
			get
			{
				return this._lINEOFBUSINESSID;
			}
			set
			{
				this._lINEOFBUSINESSID = value;
			}
		}
		
		private string _cAUPORTALPROEMAIL;
		public virtual string CAUPORTALPROEMAIL
		{
			get
			{
				return this._cAUPORTALPROEMAIL;
			}
			set
			{
				this._cAUPORTALPROEMAIL = value;
			}
		}
		
		private string _bANKIBAN;
		public virtual string BANKIBAN
		{
			get
			{
				return this._bANKIBAN;
			}
			set
			{
				this._bANKIBAN = value;
			}
		}
		
		private int _cAUPORTALPROALLOWINVOICE;
		public virtual int CAUPORTALPROALLOWINVOICE
		{
			get
			{
				return this._cAUPORTALPROALLOWINVOICE;
			}
			set
			{
				this._cAUPORTALPROALLOWINVOICE = value;
			}
		}
		
	}
}
#pragma warning restore 1591
