#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace PortalProAxapta	
{
	public partial class Cau_portalpro_VLinFactura
	{
		private string _iNVOICEID;
		public virtual string INVOICEID
		{
			get
			{
				return this._iNVOICEID;
			}
			set
			{
				this._iNVOICEID = value;
			}
		}
		
		private DateTime _iNVOICEDATE;
		public virtual DateTime INVOICEDATE
		{
			get
			{
				return this._iNVOICEDATE;
			}
			set
			{
				this._iNVOICEDATE = value;
			}
		}
		
		private decimal _lINENUM;
		public virtual decimal LINENUM
		{
			get
			{
				return this._lINENUM;
			}
			set
			{
				this._lINENUM = value;
			}
		}
		
		private string _pURCHID;
		public virtual string PURCHID
		{
			get
			{
				return this._pURCHID;
			}
			set
			{
				this._pURCHID = value;
			}
		}
		
		private decimal _lINEAMOUNT;
		public virtual decimal LINEAMOUNT
		{
			get
			{
				return this._lINEAMOUNT;
			}
			set
			{
				this._lINEAMOUNT = value;
			}
		}
		
	}
}
#pragma warning restore 1591
