#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace PortalProAxapta	
{
	public partial class Cau_PortalPro_VLinPedido
	{
		private string _pURCHID;
		public virtual string PURCHID
		{
			get
			{
				return this._pURCHID;
			}
			set
			{
				this._pURCHID = value;
			}
		}
		
		private decimal _lINENUM;
		public virtual decimal LINENUM
		{
			get
			{
				return this._lINENUM;
			}
			set
			{
				this._lINENUM = value;
			}
		}
		
		private string _iTEMID;
		public virtual string ITEMID
		{
			get
			{
				return this._iTEMID;
			}
			set
			{
				this._iTEMID = value;
			}
		}
		
		private string _nAME;
		public virtual string NAME
		{
			get
			{
				return this._nAME;
			}
			set
			{
				this._nAME = value;
			}
		}
		
		private decimal _pURCHQTY;
		public virtual decimal PURCHQTY
		{
			get
			{
				return this._pURCHQTY;
			}
			set
			{
				this._pURCHQTY = value;
			}
		}
		
		private string _pURCHUNIT;
		public virtual string PURCHUNIT
		{
			get
			{
				return this._pURCHUNIT;
			}
			set
			{
				this._pURCHUNIT = value;
			}
		}
		
		private decimal _pURCHPRICE;
		public virtual decimal PURCHPRICE
		{
			get
			{
				return this._pURCHPRICE;
			}
			set
			{
				this._pURCHPRICE = value;
			}
		}
		
		private decimal _lINEAMOUNT;
		public virtual decimal LINEAMOUNT
		{
			get
			{
				return this._lINEAMOUNT;
			}
			set
			{
				this._lINEAMOUNT = value;
			}
		}
		
		private string _eSTADO;
		public virtual string ESTADO
		{
			get
			{
				return this._eSTADO;
			}
			set
			{
				this._eSTADO = value;
			}
		}
		
		private decimal _rEMAINPURCHPHYSICAL;
		public virtual decimal REMAINPURCHPHYSICAL
		{
			get
			{
				return this._rEMAINPURCHPHYSICAL;
			}
			set
			{
				this._rEMAINPURCHPHYSICAL = value;
			}
		}
		
		private decimal _rEMAINPURCHFINANCIAL;
		public virtual decimal REMAINPURCHFINANCIAL
		{
			get
			{
				return this._rEMAINPURCHFINANCIAL;
			}
			set
			{
				this._rEMAINPURCHFINANCIAL = value;
			}
		}
		
		private DateTime? _fECHARECEPCION;
		public virtual DateTime? FECHARECEPCION
		{
			get
			{
				return this._fECHARECEPCION;
			}
			set
			{
				this._fECHARECEPCION = value;
			}
		}
		
	}
}
#pragma warning restore 1591
